### ISSUE TITLE
do you have the source code of this game 

### ISSUE THREAD

**Issue by zhou21475** [JackyKit123/randomdice.gg#2]
do you have the source code of this game ,

**Comment by Chestnut5113** [comment]
We are NOT offical developers, and we DON'T have any source code of this game, please don't ask again, thank you!

**Comment by imkunet** [comment]
The source code of the RandomDice game is property of 111% and is not controlled/distributed by the randomdice.gg site. If you want to request a copy from the publisher directly, email `help@111percent.net`. 

I personally am quite dubious as to whether they grant you the code at all. Game developers like to keep their code closed source to prevent clones/stealing the game/cheaters.
